from typing import Protocol, List, Dict, Any, Optional
from .domain import TaskSpec, CompletionRecord


class LLMProvider(Protocol):
    def name(self) -> str: ...
    def versions(self) -> List[str]: ...
    def generate(self, task: TaskSpec, version: str) -> CompletionRecord: ...


class MetricsEngine(Protocol):
    def compute(self, completions: List[CompletionRecord]) -> List[Dict[str, Any]]: ...


class AnalysisEngine(Protocol):
    def analyze(self, metrics_rows: List[Dict[str, Any]]) -> Dict[str, Any]: ...


class StorageRepository(Protocol):
    def save_rows(self, rows: List[Dict[str, Any]], table: str, partition: Optional[str] = None) -> None: ...
    def load_rows(self, table: str, partition: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def exists(self, table: str, partition: Optional[str] = None) -> bool: ...
